### PR TITLE
git: update .gitignore file to exclude more file extensions

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by andrewbird** [comment]
I have a general question here. Why is there so much use of the .gitignore file on fdos projects? I work on other projects that either don't have one, or it's minimal. In that case don't ever commit files that shouldn't done, or miss ones that should. Is there another reason?

**Comment by jmalak** [comment]
it simplify what is visible for git.
Also GUI git applications use this file to filter what you see by various filter. below is example of Freecom tree from GUI on Linux
image

**Comment by jmalak** [comment]
yes and also you don't see any intermadiate files if you put it into gitignore file.
I added mostly extension to gitignore that any file with such extension anywhere is hidden.

**Comment by andrewbird** [comment]
I guess I just use the command line which shows only files of known to git, intermediates won't appear etc

`git diff` # to see what's changed
`git add filename` # to add a new file
`git commit -a` # to commit changes and including new files added

**Pull request merged**
