### PR TITLE
build: modify echolib.bat to minimize environment use and args check

### PR DESCRIPTION
**Pull request by jmalak**
- change to be similar as echoto.bat nethod
- no more then 10 parameters are used
- add arguments overflow check to echolib.bat
- add arguments overflow check to echoto.bat

### CODE REVIEW

**Comment by andrewbird** [comment]
Hi @jmalak I'm currently trying to get TurboC 2.01 compiling again and have hit the max args with echoto.bat. Is it possible to save the 1st arg to a variable and shift, so getting to use one more arg? It seemed to work for me, but I'm not really understanding the environment space issue with dos and wouldn't like to recreate the original problem.
```diff
ajb@calypso:/clients/common/fdos/freecom.git$ git show 770f500cdbd83d94223c48c5fdbbb19fd5d36c79
commit 770f500cdbd83d94223c48c5fdbbb19fd5d36c79
Author: Andrew Bird <ajb@spheresystems.co.uk>
Date:   Sun Dec 22 00:54:09 2024 +0000

    Build: Turbo C needs another arg from echoto

diff --git a/scripts/echoto.bat b/scripts/echoto.bat
index d792a4c..ddcae9a 100644
--- a/scripts/echoto.bat
+++ b/scripts/echoto.bat
@@ -1,4 +1,6 @@
 @echo off
-if "%2%3%4%5%6%7%8%9" == "" goto nothing
-echo %2 %3 %4 %5 %6 %7 %8 %9 >>%1
+set FILE=%1
+shift
+if "%1%2%3%4%5%6%7%8%9" == "" goto nothing
+echo %1 %2 %3 %4 %5 %6 %7 %8 %9 >> %FILE%
 :nothing
```

**Comment by jmalak** [comment]
I am also not remembering on original problem now.
It was related to compilation with Turbo C on pure DOS and with limited size of environment space that only solution was to remove any writing to environment variables.
Under another condition it doesn't happen.
I think that replace it by two calls to echoto.bat is more reliable under any conditions.
On DOS it is safe if you don't use any environment variables and write it directly to response file.
I am thinking about "&" character escaping in echolib to remove environment variable.

**Comment by andrewbird** [comment]
> I think that replace it by two calls to echoto.bat is more reliable under any conditions.

Okay, I've changed things here to use two CFLAGS variables, and updated the ${COMPILER}.mak files (there are others apart from tc2)

**Comment by jmalak** [comment]
If I remember properly then TC is combination of turboc.cfg file and command line.
that common setup can be modified in turboc.cfg and rest in response file.

**Comment by andrewbird** [comment]
I'm seeing a slight problem with this and Turbo C 2.01. The old script produced this
~~~
+addu.obj +byte2par.obj +cntry.obj +dfndeli2.obj +dfndelim.obj +dfnexpan.obj +dfnfnam.obj &
+dfnfullp.obj +dfnmerge.obj +dfnpath.obj +dfnsplit.obj +dfnsquee.obj +dfnstat.obj &
+dfntruen.obj +dmemcmpf.obj +dosalloc.obj +dosfree.obj +dossize.obj +dstrchar.obj &
~~~

whereas the new produces

~~~
addu.obj byte2par.obj cntry.obj dfndeli2.obj dfndelim.obj dfnexpan.obj dfnfnam.obj  &
dfnfullp.obj dfnmerge.obj dfnpath.obj dfnsplit.obj dfnsquee.obj dfnstat.obj   & 
dfntruen.obj dmemcmpf.obj dosalloc.obj dosfree.obj dossize.obj dstrchar.obj   & 
~~~

TLINK then complains about unexpected character 'a'

**Comment by jmalak** [comment]
for now it will be best to return echolib.bat to original version.
the issue is that only Turbo C require (+) character before object module file which I omitted.

**Pull request merged**
