### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by petr-akhlamov**
Fix translation.

### CODE REVIEW

**Comment by andrewbird** [comment]
Why is the diff here so big, surely not every line changed? I suspect that's why it hasn't been applied.

**Comment by PerditionC** [comment]
Yes, because the whole file changed and I don't know Russian it's harder for me to verify the translation.  I'm slowly progressing through patches and once I verify it works and a basic verification of what the translation says I will commit it.  I apologise for taking so long.  I appreciate all the translation work because I don't have enough fluency to do any.

**Comment by andrewbird** [comment]
Mmm, there's something odd with the encoding of the new translation, consider

#### Old
~~~
:TEXT_DIR_HDR_SERIAL_NUMBER
 Серийный номер тома - %04X-%04X
~~~

#### New
~~~
:TEXT_DIR_HDR_SERIAL_NUMBER#0%
Серийный номер: X-X
~~~

The new one replaces the printf formatting "%04" with ^D

**Comment by andrewbird** [comment]
I did an experiment with `.gitattributes` setting an encoding to see if Github and `git diff` give better diffs see https://github.com/andrewbird/freecom/commit/f1f2b50e34c34a1a33af2be08b10fa3b75af8d89. The idea is that internally git keeps the files internally as utf8 and on user checkout they are converted to have the codepage specified and the line endings to match the platform being worked on. That way people can just edit the files with their usual tools, and on commit they are normalised for everyone else. I think it looks a lot better. I used the updated 'russian.lng' from #32 for the test, but I've no idea if that's actually correct. Anyway what do you think? To use it properly we'd have to rename the translation files to a nice pattern say 'spanish.lng' => 'es_ES850.lng',  'french.lng' -> 'fr_FR850.lng', and 'pt_br.lng' => pt_BR850.lng etc.

**Comment by PerditionC** [comment]
Interesting idea.  I think we need some translators to comment.  Ultimately I would like to move to a method that eases translation work and shares translations among the various utilities for any overlap.  That said, including the expected display code page in the name and storing as unicode goes towards that goal as I think the translation text should be in utf8 and transcoded to appropriate code pages during build process.  I want to try some things and maybe bring up on the mailing list first before doing sweeping renames.

**Comment by andrewbird** [comment]
> I think the translation text should be in utf8 and transcoded to appropriate code pages during build process.

Absolutely, that was my ideal scenario too! However, since I'm new here I didn't want to inconvenience people building on DOS by adding some as yet unknown step (on Linux or Windows we can do the conversion during build using iconv).

> I want to try some things and maybe bring up on the mailing list first before doing sweeping renames.

My renaming was just to reduce the wordiness in the `.gitattributes` file, the translations could all be explicit and the change would be transparent to all except people(i.e. you) viewing the diff when deciding whether to apply.

**Comment by bitigchi** [comment]
I can review the translations, but I need help in deciphering the files. :)

**Comment by andrewbird** [comment]
@petr-akhlamov I did a little work to try to fix the conflict of your PR with current master (see adfc0a6), it would now apply okay but it seems like it's not finished yet? If you want to work on it further, please feel free to grab my edited version as that would make a good start. Thanks.

@PerditionC Please don't apply my reworked version, I place it here only as a reference point, thanks.

**Pull request closed without merging**
