### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by ghderty**
https://sourceforge.net/p/freedos/bugs/298/
some changes are partially taken from #19

### CODE REVIEW

**Comment by bitigchi** [comment]
LGTM!

**Comment by andrewbird** [comment]
Perhaps squash the two commits, as one introduces changes then the latter corrects them?

**Comment by ghderty** [comment]
I'm not very familiar with git, sorry.

Also, in the second commit I uploaded the russian.lng in UTF-8 encoding since with current master, CP866 was generating a big diff. Not sure if this is correct way.

**Comment by andrewbird** [comment]
It has to be cp866, I'll check what you have.

**Comment by andrewbird** [comment]
It looks fine, but I'm not sure quite how the conversion from utf-8 to cp866 occurred.
Did the strings `TEXT_STRING_PM` and `TEXT_STRING_AM` not need to be translated, as they were originally?

**Comment by ghderty** [comment]
The files were uploaded via the web interface, maybe this caused the problems with the encoding in the first commit?

>Did the strings TEXT_STRING_PM and TEXT_STRING_AM not need to be translated, as they were originally?

There was originally written simply am/pm but in cyrillic.
In russian it is usually used either same am/pm or less often дп/пп. 
https://ru.wikipedia.org/wiki/12-%D1%87%D0%B0%D1%81%D0%BE%D0%B2%D0%BE%D0%B9_%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82_%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8
So I chose the first one.

**Comment by andrewbird** [comment]
As long as the am/pm wasn't an oversight that's cool.

**Comment by andrewbird** [comment]
So I did a little experimentation with a copy of your branch. I can only think that the first commit was a cherry-pick of an earlier commit as it had the old encoding. The second commit was effectively just rewriting that internally to utf-8 and the following two commits were as expected. It is possible to right this but it requires a little git foo (rebase / edit at each stage and `git add --renormalize .`). If that's done the second commit becomes empty, but I'm not going to ask you to do that as it's not easy for me to describe a procedure and expect it done without us ending up in a pickle. If you are bothered I've put up my fixed up copy of your branch here https://github.com/andrewbird/freecom/tree/ghderty-patch-1

**Comment by ghderty** [comment]
After the second commit, I continued to upload files in UTF8 using the browser as well.

**Comment by andrewbird** [comment]
I'd like to avoid the committing your commit with the incorrect encoding, so I wonder if you'd mind me rebasing/squashing your commits when you are happy and @PerditionC can review / merge that? Of course it'll still have your attribution on the final commit. If so, just let me know when you are ready to merge, please?

**Comment by ghderty** [comment]
I think I'm done. I am not really familiar with the development stuff and do not really care about my attribution etc so you can do whatever is more convenient.

**Pull request closed without merging**
