### PR TITLE
Improve Turkish translations

### PR DESCRIPTION
**Pull request by bitigchi**
Includes improvements for previously missed strings. Adds a missing string from DEFAULT.lng as well.

Edit: I am not sure why it shows merge conflicts. Any ideas why?

### CODE REVIEW

**Comment by PerditionC** [comment]
I believe the conflict is due to a recent change to how the lng files are stored in git.  They are now stored as utf8 and converted to local code page on checkout by git.  At least that's what is supposed to happen.  There are probably easier ways to fix, but I think a simple fix is do a fresh check out, copy this updated file over and re commit changes.  I will merge the changes this weekend unless you want to try it.   The goal is to get things easier for translators and avoid corruption due to code page mismatches.  Sorry for the current conflicts.

**Comment by bitigchi** [comment]
Oh okay. I'll upload a UTF-8 version then, no problem. It's a welcome improvement actually.

**Comment by andrewbird** [comment]
Hi @bitigchi yes, it's because since you last pulled from FDOS/freecom master the internal encodings on .lng and .err got set to utf-8 so that a proper diff can be seen. This method should work for you to resolve the conflicts.
~~~
git branch -m master mytopic
git checkout HEAD~1
git checkout -b master
git pull upstream
git show mytopic:strings/turkish.lng > strings/turkish.lng
git diff # should now show your changes
git commit -a -m "Improve Turkish translations "
git push -f origin master
~~~

Note: this assumes that origin is set to repo at bitigchi, upstream == FDOS

BTW, you can't upload utf-8, that encoding is git internal only

**Comment by andrewbird** [comment]
So using the method above (with .err too) here's what I get
https://github.com/andrewbird/freecom/commit/73ee73b755ac62f5c16b994d3c62a78416e1b922

**Comment by bitigchi** [comment]
I think I am doing something wrong. Is it okay if I close this and we use your version? :)

**Comment by andrewbird** [comment]
It's okay by me, but it would be better with your name on the commit.

I think the problem is because you have multiple commits and the intermediate ones still have the conflict. That's why in the example above, I renamed your master, checked out a suitable revision before any of your latest commits, then made a new master and pulled from upstream. That done, the 'git show' of the new files from the renamed branch was so that we got the file contents without the metadata.

**Comment by bitigchi** [comment]
Okay, I'll start fresh.

**Comment by bitigchi** [comment]
I am getting slightly different output now... I guess it's progress. However, this is much frustrating, I'll give a break now.

**Comment by andrewbird** [comment]
so what codepage did you use, it should still be cp857?

**Comment by bitigchi** [comment]
Yes, I used CP 857. My steps were:

- Commit CP 857 files whilst on master branch
- Follow instructions above

I used TextEdit on macOS to save using Turkish (DOS) encoding.

**Comment by andrewbird** [comment]
And the text still looks correct in the local files?

**Comment by bitigchi** [comment]
Yes, indeed. There are no issues displaying Turkish characters using TextEdit. Vim displays <XX> for the converted characters, but well, that's Vim.

**Comment by andrewbird** [comment]
Did you push, because I'm seeing UTF-8 on your branch
~~~
$ file strings/turkish.err
strings/turkish.err: UTF-8 Unicode text
~~~

**Comment by bitigchi** [comment]
Oh, just did.

**Comment by andrewbird** [comment]
Cool that looks better, you just need to squash those two commits now!

**Comment by bitigchi** [comment]
I guess so! Will do and report back with a PR. Thanks for your time!

**Comment by andrewbird** [comment]
Good stuff, and thanks for persevering!

**Pull request closed without merging**
